#!/usr/bin/env bash
# Run OdorSim/GADEN verification for 30 NEW random seeds with obstacle 8x8 config.
# These seeds are generated by numpy.random.default_rng(2028) and exclude all
# seeds used in previous batches.
# Usage (from WSL, after sourcing OdorSim/setup/activate.sh):
#   bash scripts/run_odorsim_obstacle_30seeds_v3.sh
set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SEEDS="56541 38675 35694 59255 23488 73733 33511 98492 96264 84224 30991 39958 41850 82929 64497 47843 95012 39036 22771 7343 34564 1415 68933 27165 7960 89797 81069 59446 71823 64124"
ENV_CONFIG="config/warehouse_obstacle_8x8.yaml"
OUT_DIR="$PROJECT_ROOT/outputs/odorsim_obstacle_new30_v3"
SCENARIO="$PROJECT_ROOT/odorsim_scenarios/warehouse_8x8/environment_configurations/config1"

mkdir -p "$OUT_DIR"
cd "$PROJECT_ROOT"

for seed in $SEEDS; do
    echo "==================== seed $seed ===================="
    if ! python scripts/run_odorsim_verification.py \
        --seed "$seed" \
        --max-steps 2000 \
        --env-config "$ENV_CONFIG" \
        --scenario "$SCENARIO" \
        --out-dir "$OUT_DIR" \
        --video-stride 2 \
        --fps 20 \
        --no-video; then
        echo "[WARN] seed $seed failed"
    fi
done

echo "==================== Aggregate evaluation ===================="
python scripts/evaluate_odorsim_runs.py \
    --out-dir "$OUT_DIR" \
    --seeds $SEEDS \
    --save-json "$OUT_DIR/aggregate_evaluation.json"

echo "==================== Detailed analysis ===================="
python scripts/analyze_odorsim_runs.py \
    --out-dir "$OUT_DIR" \
    --seeds $SEEDS \
    --output "$OUT_DIR/analysis.md"
